import Head from "next/head";
import { useState } from "react";

export default function Home() {
  const [value, setValue] = useState("");
  const [amazon, setAmazon] = useState("https://www.amazon.co.jp/s?k=");
  // const [rakuten, setRakuten] = useState("");
  const [merukari, setMerukari] = useState("https://jp.mercari.com/search?keyword=");
  const [door, setDoor] = useState("");
  const [google, setGoogle] = useState("");
  const [youtube, setYoutube] = useState("");

  const handleInput = (e: React.ChangeEvent<HTMLInputElement>) => {
    setValue(e.target.value);
  };

  const handleReset=()=>{
    window.location.reload()
  }

  const handleSubmit = (e: React.FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    setAmazon(`https://www.amazon.co.jp/s?k=${value}`);
    // setRakuten(`https://search.rakuten.co.jp/search/mall/${value}`);
    setMerukari(`https://jp.mercari.com/search?keyword=${value}`);
    setDoor(
      `https://doors.doshisha.ac.jp/opac/opac_search/?lang=0&amode=2&appname=Netscape&version=5&cmode=0&smode=0&kywd=${value}&index_amazon_s=Books&node_s=`
    );
    setGoogle(`https://www.google.com/search?q=${value}`)
    setYoutube(`https://www.youtube.com/results?search_query=${value}`)

  };
  return (
    <div>
      <Head>
        <title>Search App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="m-10">
        <h1 className="text-2xl">同時検索アプリ</h1>

        <div className="mt-5">
          <form className="flex" onSubmit={(e) => handleSubmit(e)}>
            <input
              className="border-2 border-gray-700 rounded w-2/4 focus:outline-none p-2"
              type="text"
              onChange={handleInput}
              placeholder="検索キーワードを入力"
              value={value}
            />
            <button
              type="submit"
              className="border-2 border-gray-700 rounded p-2 bg-slate-700 text-gray-50"
            >
              set
            </button>
            <button
              type="button"
              onClick={handleReset}
              className="border-2 border-red-400 rounded p-2 bg-red-400 text-gray-50 ml-1 hover:bg-red-500 hover:border-red-500"
            >
              reset
            </button>
          </form>
        </div>

        <div>
          <ul className="mt-10">
            <li className="flex my-1">
              <a
                className="border-2 border-gray-400 w-1/4 rounded p-2"
                href={amazon}
                target="_blank"
                rel="noopener noreferrer"
              >
                Amazonで検索
              </a>
            </li>
            <li className="flex my-1">
              <a
                className="border-2 border-gray-400 w-1/4 rounded p-2"
                href={merukari}
                target="_blank"
                rel="noopener noreferrer"
              >
                メルカリで検索
              </a>
            </li>
            <li className="flex my-1">
              <a
                className="border-2 border-gray-400 w-1/4 rounded p-2"
                href={door}
                target="_blank"
                rel="noopener noreferrer"
              >
                図書館で検索
              </a>
            </li>
            <li className="flex my-1">
              <a
                className="border-2 border-gray-400 w-1/4 rounded p-2"
                href={google}
                target="_blank"
                rel="noopener noreferrer"
              >
                Googleで検索
              </a>
            </li>
            <li className="flex my-1">
              <a
                className="border-2 border-gray-400 w-1/4 rounded p-2"
                href={youtube}
                target="_blank"
                rel="noopener noreferrer"
              >
                YouTubeで検索
              </a>
            </li>
            {/* <li className="flex my-1">
              <a
                className="border-2 border-gray-400 w-1/4 rounded p-2"
                href={rakuten}
                target="_blank"
                rel="noopener noreferrer"
              >
                楽天で検索
              </a>
            </li> */}
          </ul>
        </div>
      </div>
    </div>
  );
}
